# Generated by Django 3.0.6 on 2020-05-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('Aut_id', models.AutoField(primary_key=True, serialize=False)),
                ('Aut_nombre', models.CharField(max_length=100, verbose_name='Aut_nombre')),
                ('Aut_correo', models.CharField(max_length=200, verbose_name='Aut_correo')),
                ('Aut_telefono', models.CharField(max_length=200, verbose_name='Aut_telefono')),
                ('Aut_fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cli_nombre', models.CharField(max_length=100, verbose_name='Cli_nombre')),
                ('Cli_correo', models.CharField(max_length=200, verbose_name='Cli_correo')),
                ('Cli_telefono', models.CharField(max_length=200, verbose_name='Cli_telefono')),
                ('Cli_fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Lib_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lib_nombre', models.CharField(max_length=100, verbose_name='Aut_nombre')),
                ('Lib_precio', models.IntegerField(default=20000)),
                ('Lib_cantidad', models.IntegerField(default=0)),
                ('Lib_fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Ven_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ven_cantidad', models.IntegerField(default=0)),
                ('Ven_fecha', models.DateTimeField(verbose_name='date published')),
                ('Cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
                ('Lib_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Autor')),
                ('Lib_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Libro')),
            ],
        ),
    ]
